;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Items",DevComment="Tag that is the root for all tags that are assigned to specific items. Item name = Tag")
GameplayTagList=(Tag="Items.Equipment",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing.Armour",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing.Boots",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing.Bottoms",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing.Glove",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing.Headwear",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Clothing.Outwear",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Other",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Other.Fleshlight",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Storage.Backpack",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Storage.Bag",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Weapon.Melee.Knife",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Weapon.Range.Pistol",DevComment="")
GameplayTagList=(Tag="Items.Equipment.Weapon.Range.Rifle",DevComment="")
GameplayTagList=(Tag="Items.Puzzles",DevComment="")
GameplayTagList=(Tag="Items.Puzzles.HeadStatuePuzzle",DevComment="")
GameplayTagList=(Tag="Items.Puzzles.Horse",DevComment="")
GameplayTagList=(Tag="Items.Resurse",DevComment="")
GameplayTagList=(Tag="Items.Resurse.Ammo",DevComment="")
GameplayTagList=(Tag="Items.Resurse.Ammo.12x24mm",DevComment="")
GameplayTagList=(Tag="Items.Resurse.Ammo.7-62x39mm",DevComment="")
GameplayTagList=(Tag="Items.Resurse.Ammo.9x18mm",DevComment="")
GameplayTagList=(Tag="Items.Resurse.Canister",DevComment="")
GameplayTagList=(Tag="Items.Resurse.Keys",DevComment="")
GameplayTagList=(Tag="Items.Used",DevComment="")
GameplayTagList=(Tag="Items.Used.Bottle",DevComment="")
GameplayTagList=(Tag="Items.Used.Can",DevComment="")
GameplayTagList=(Tag="Items.Used.Food",DevComment="")

