;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Blocked",NewTagName="Blocked")
+GameplayTagRedirects=(OldTagName="Blocked.Damage",NewTagName="Blocked.Damage")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Armour",NewTagName="Items.Equipment.Clothing.Armour")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Glove",NewTagName="Items.Equipment.Clothing.Glove")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Backpack",NewTagName="Items.Equipment.Clothing.Backpack")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Boots",NewTagName="Items.Equipment.Clothing.Boots")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Headwear",NewTagName="Items.Equipment.Clothing.Headwear")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Bottoms",NewTagName="Items.Equipment.Clothing.Bottoms")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Bag",NewTagName="Items.Equipment.Storage.Bag")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Clothing.Backpack",NewTagName="Items.Equipment.Storage.Backpack")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Knife",NewTagName="Items.Equipment.Weapon.Melee.Knife")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Outwear",NewTagName="Items.Equipment.Clothing.Outwear")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Pistol",NewTagName="Items.Equipment.Weapon.Range.Pistol")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Pistol.Makarov",NewTagName="Items.Equipment.Range.Pistol.Makarov")
+GameplayTagRedirects=(OldTagName="Items.Equipment.Shogtun",NewTagName="Items.Equipment.Range.Shotgun")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

